<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="us" nsURI="UsModel" nsPrefix="UsModel">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="USNode" eSuperTypes="#//UsPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//UsElement" containment="true">
      <eAnnotations source="gmf.compartment"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsPart">
    <eAnnotations source="gmf.node">
      <details key="label" value="description"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UsElement" eSuperTypes="#//UsPart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//UsElementType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UsElementType">
    <eLiterals name="ROLE"/>
    <eLiterals name="ACTION" value="1"/>
    <eLiterals name="GOAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="USModel">
    <eAnnotations source="gmf.diagram">
      <details key="model.extension" value="us"/>
      <details key="diagram.extension" value="usdiagram"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uss" upperBound="-1" eType="#//USNode"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
